<a href="https://colab.research.google.com/github/iamkuntaldinda/Assignment/blob/main/EmailSpam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#describe : this program detects if an email is spam or not 

In [1]:
import numpy as np
import pandas as  pd 
import nltk 
from nltk.corpus import stopwords 
import string


In [2]:
import sklearn
print (sklearn.__version__)

0.22.2.post1


In [3]:
#load the data 
from google.colab import files
uploaded = files.upload()

Saving emails.csv to emails.csv


In [4]:
 df = pd.read_csv('emails.csv')
 df.head(5)
 

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [5]:
#print the shape
df.shape

(5728, 2)

In [6]:
#get the common name 
df.columns

Index(['text', 'spam'], dtype='object')

In [7]:
#check for duplicates and remove them 
df.drop_duplicates(inplace=True)

In [8]:
#show the new shape 
df.shape

(5695, 2)

In [9]:
#show the number of missing(NAN ,na ,NaN) data from each column
df.isnull().sum()

text    0
spam    0
dtype: int64

In [10]:
# download the Stopwords package 
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [11]:
def process_text(text):
  #1 remove the punctuation
  #2 remove stopowrds 
  #3 return a list of clean test words 
  #1 
  nopunc = [char for char in text if char not in string.punctuation]
  nopunc = ''.join(nopunc)

  #2 
  clean_words = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
  #3 
  return clean_words




In [12]:
# show the tokenization (a list of token also called lemmas)
df['text'].head().apply(process_text)



0    [Subject, naturally, irresistible, corporate, ...
1    [Subject, stock, trading, gunslinger, fanny, m...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, money, get, software, cds, software,...
Name: text, dtype: object

In [14]:
 #example 
 message4 = 'hello world hello world '
 message5 = 'hello hello hello play ball cricket'
 print(message4)

 # convert the text to a matrix of token counts
 from sklearn.feature_extraction.text import CountVectorizer
 bow4 = CountVectorizer(analyzer=process_text).fit_transform([[message4], [message5]])
 print(bow4)
 print()
 print(bow4.shape)

hello world hello world 
  (0, 2)	2
  (0, 4)	2
  (1, 2)	3
  (1, 3)	1
  (1, 0)	1
  (1, 1)	1

(2, 5)


In [15]:
#convert a collection of text to a matriz of token
from sklearn.feature_extraction.text import CountVectorizer 
messages_bow = CountVectorizer(analyzer= process_text).fit_transform(df['text'])


In [16]:
from sklearn.model_selection  import  train_test_split
X_train , X_test , y_train , y_test  = train_test_split(messages_bow, df['spam'] , test_size = 0.20 , random_state = 0 )



In [17]:
# GET the shape 
messages_bow.shape 

(5695, 37229)

In [18]:
# crate and train the Naive Bayes Classifier 
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(X_train, y_train)

In [21]:
print(classifier.predict(X_train))

print(y_train)

[0 0 0 ... 0 0 0]
3337    0
2104    0
3905    0
461     1
314     1
       ..
4950    0
3273    0
1653    0
2611    0
2736    0
Name: spam, Length: 4556, dtype: int64


In [28]:
# evaluate the model on the taring data set   

from sklearn.metrics import classification_report, confusion_matrix , accuracy_score 
pred = classifier.predict(X_train)
print(classification_report(y_train , pred))
print()
print('Confusion Matrix:\n ', confusion_matrix(y_train, pred))
print('Accuracy' , accuracy_score(y_train, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3457
           1       0.99      1.00      0.99      1099

    accuracy                           1.00      4556
   macro avg       0.99      1.00      1.00      4556
weighted avg       1.00      1.00      1.00      4556


Confusion Matrix:
  [[3445   12]
 [   1 1098]]
Accuracy 0.9971466198419666


In [29]:
# print the prediction
print(classifier.predict(X_test))

# Print the actual values 
print(y_test.values)

[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]


In [30]:
# evaluate the model on the taring data set   

from sklearn.metrics import classification_report, confusion_matrix , accuracy_score 
pred = classifier.predict(X_test)
print(classification_report(y_test , pred))
print()
print('Confusion Matrix:\n ', confusion_matrix(y_test, pred))
print('Accuracy' , accuracy_score(y_test, pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       870
           1       0.97      1.00      0.98       269

    accuracy                           0.99      1139
   macro avg       0.98      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139


Confusion Matrix:
  [[862   8]
 [  1 268]]
Accuracy 0.9920983318700615
